const form = document.getElementById('formulario');
    form.addEventListener('submit', vizualizar) //adicionar um tipo de evento ao clicar em converter
const group = document.getElementsByClassName('form-group')
const nome = document.getElementById('nome')
const dia = document.getElementById('dia')
const res = document.getElementById('resultado')


function criarTabela(conteudo){
    var tabela = document.createElement("table");
    var thead = document.createElement("thead");
    var tbody=document.createElement("tbody");
    var thd=function(i){return (i==0)?"th":"td";};
    for (var i=0;i<conteudo.length;i++) {
        var tr = document.createElement("tr");
        for(var o=0;o<conteudo[i].length;o++){
        var t = document.createElement(thd(i));
        t.innerHTML = "<td><button onclick='alert('$id')'>$id</button></td>"
        var texto=document.createTextNode(conteudo[i][o]);
        t.appendChild(texto);
        tr.appendChild(t);
    }
    (i==0)?thead.appendChild(tr):tbody.appendChild(tr);
  }
  tabela.appendChild(thead);
  tabela.appendChild(tbody);
  return tabela;
}

function vizualizar(){
    if(!nome.value || nome.value == ''){
        window.alert('Selecione um nome!')
        return;
    }else if(dia.value == ''){
        window.alert('Selecione um dia!')
        return;
    }
    if (nome.value == 'Lary'){
        if(dia.value === 'seg'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Extensora</td>',
                    '<td>4</td>',
                    '<td>40kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Flexora-uni</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Agachamento livre</td>',
                    '<td>3</td>',
                    '<td>30kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Afundo</td>',
                    '<td>3</td>',
                    '<td>12kg</td>',
                '</tr>',
                '</tbody>',
                '</table>',
        
                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Remada-uni</td>',
                    '<td>4</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-barra</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n\n\n");
        }else if(dia.value === 'ter'){
            res.innerHTML = 'DIA DE DESCANSO!\n 🥳✨🥳'
        }else if(dia.value === 'qua'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Agachamento sumõ</td>',
                    '<td>4</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Elevação pélvica</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Búlgaro</td>',
                    '<td>4</td>',
                    '<td>12kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff-uni</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '</tbody>',
                '</table>',
                
                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'qui'){
            res.innerHTML = 'DIA DE DESCANSO!\n 🎉🥳🎉'
        }else if(dia.value == 'sex'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Extensora-uni</td>',
                    '<td>4</td>',
                    '<td>40kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Flexora</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Agachamento livre</td>',
                    '<td>3</td>',
                    '<td>30kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Avanço</td>',
                    '<td>3</td>',
                    '<td>12kg</td>',
                '</tr>',
                '</tbody>',
                '</table>',

                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Remada-uni</td>',
                    '<td>4</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-barra</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'sab'){
            res.innerHTML = 'DIA DE DESCANSO!\n 🥳🎊🥳'
        }
    }

    else if(nome.value === 'Gisa'){
        if(dia.value === 'seg'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Agachamento sumõ</td>',
                    '<td>4</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Elevação pélvica</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Búlgaro</td>',
                    '<td>4</td>',
                    '<td>12kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if (dia.value === 'ter'){
            res.innerHTML = [
                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Remada-uni</td>',
                    '<td>4</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-barra</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'qua'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Extensora-uni</td>',
                    '<td>3</td>',
                    '<td>45kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Flexora</td>',
                    '<td>3</td>',
                    '<td>25kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Agachamento livre</td>',
                    '<td>3</td>',
                    '<td>30kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Afundo</td>',
                    '<td>3</td>',
                    '<td>6kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'qui'){
            res.innerHTML = [
                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'sex'){
            res.innerHTML = [
                '<capition>Exercicios Inferiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Agachamento sumõ</td>',
                    '<td>4</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Elevação pélvica</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Avanço</td>',
                    '<td>4</td>',
                    '<td>12kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Stiff-uni</td>',
                    '<td>3</td>',
                    '<td>31kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }else if(dia.value === 'sab'){
            res.innerHTML = [
                '<capition>Exercicios Superiores\n</capition>',
                '<table>',
                '<thead>',
                '<tr>',
                    '<th>Exercicio</th>',
                    '<th>Séries</th>',
                    '<th>Peso</th>',
                '</tr>',
                '</thead>',

                '<tbody>',
                '<tr>',
                    '<td>Bíceps-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Remada-barra</td>',
                    '<td>3</td>',
                    '<td>10kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Remada-uni</td>',
                    '<td>4</td>',
                    '<td>5kg</td>',
                '</tr>',
                '<tr>',
                    '<td>Supino-barra</td>',
                    '<td>3</td>',
                    '<td>20kg</td>',
                '</tr>',
                /*'<tr>',
                    '<td>Supino-uni</td>',
                    '<td>3</td>',
                    '<td>5kg</td>',
                '</tr>',*/
                '<tr>',
                    '<td>Abdominais</td>',
                    '<td>5 tipos</td>',
                    '<td>Várias</td>',
                '</tr>',
                '</tbody>',
                '</table>',
            ].join("\n");
        }
    } 
}